// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: lexatic-backend/provider-api.proto

package lexatic_backend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProviderService_GetAllModel_FullMethodName       = "/provider_api.ProviderService/GetAllModel"
	ProviderService_GetAllModelHealth_FullMethodName = "/provider_api.ProviderService/GetAllModelHealth"
	ProviderService_GetAllProvider_FullMethodName    = "/provider_api.ProviderService/GetAllProvider"
	ProviderService_GetModel_FullMethodName          = "/provider_api.ProviderService/GetModel"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderServiceClient interface {
	GetAllModel(ctx context.Context, in *GetAllModelRequest, opts ...grpc.CallOption) (*GetAllModelResponse, error)
	GetAllModelHealth(ctx context.Context, in *GetAllModelHealthRequest, opts ...grpc.CallOption) (*GetAllModelHealthResponse, error)
	GetAllProvider(ctx context.Context, in *GetAllProviderRequest, opts ...grpc.CallOption) (*GetAllProviderResponse, error)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) GetAllModel(ctx context.Context, in *GetAllModelRequest, opts ...grpc.CallOption) (*GetAllModelResponse, error) {
	out := new(GetAllModelResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetAllModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetAllModelHealth(ctx context.Context, in *GetAllModelHealthRequest, opts ...grpc.CallOption) (*GetAllModelHealthResponse, error) {
	out := new(GetAllModelHealthResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetAllModelHealth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetAllProvider(ctx context.Context, in *GetAllProviderRequest, opts ...grpc.CallOption) (*GetAllProviderResponse, error) {
	out := new(GetAllProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetAllProvider_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error) {
	out := new(GetModelResponse)
	err := c.cc.Invoke(ctx, ProviderService_GetModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
// All implementations should embed UnimplementedProviderServiceServer
// for forward compatibility
type ProviderServiceServer interface {
	GetAllModel(context.Context, *GetAllModelRequest) (*GetAllModelResponse, error)
	GetAllModelHealth(context.Context, *GetAllModelHealthRequest) (*GetAllModelHealthResponse, error)
	GetAllProvider(context.Context, *GetAllProviderRequest) (*GetAllProviderResponse, error)
	GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error)
}

// UnimplementedProviderServiceServer should be embedded to have forward compatible implementations.
type UnimplementedProviderServiceServer struct {
}

func (UnimplementedProviderServiceServer) GetAllModel(context.Context, *GetAllModelRequest) (*GetAllModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllModel not implemented")
}
func (UnimplementedProviderServiceServer) GetAllModelHealth(context.Context, *GetAllModelHealthRequest) (*GetAllModelHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllModelHealth not implemented")
}
func (UnimplementedProviderServiceServer) GetAllProvider(context.Context, *GetAllProviderRequest) (*GetAllProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllProvider not implemented")
}
func (UnimplementedProviderServiceServer) GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModel not implemented")
}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_GetAllModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetAllModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetAllModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetAllModel(ctx, req.(*GetAllModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetAllModelHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllModelHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetAllModelHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetAllModelHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetAllModelHealth(ctx, req.(*GetAllModelHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetAllProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetAllProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetAllProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetAllProvider(ctx, req.(*GetAllProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "provider_api.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllModel",
			Handler:    _ProviderService_GetAllModel_Handler,
		},
		{
			MethodName: "GetAllModelHealth",
			Handler:    _ProviderService_GetAllModelHealth_Handler,
		},
		{
			MethodName: "GetAllProvider",
			Handler:    _ProviderService_GetAllProvider_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _ProviderService_GetModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lexatic-backend/provider-api.proto",
}
