// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0-devel
// 	protoc        v3.20.3
// source: lexatic-backend/vault-api.proto

package lexatic_backend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderCredential struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId     uint64                 `protobuf:"varint,2,opt,name=providerId,proto3" json:"providerId,omitempty"`
	OrganizationId uint64                 `protobuf:"varint,3,opt,name=organizationId,proto3" json:"organizationId,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Key            string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Provider       string                 `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`
	Image          string                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	CreatedDate    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
}

func (x *ProviderCredential) Reset() {
	*x = ProviderCredential{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCredential) ProtoMessage() {}

func (x *ProviderCredential) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCredential.ProtoReflect.Descriptor instead.
func (*ProviderCredential) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderCredential) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProviderCredential) GetProviderId() uint64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *ProviderCredential) GetOrganizationId() uint64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *ProviderCredential) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderCredential) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProviderCredential) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProviderCredential) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderCredential) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProviderCredential) GetCreatedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedDate
	}
	return nil
}

type CreateProviderCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderId  uint64 `protobuf:"varint,1,opt,name=providerId,proto3" json:"providerId,omitempty"`
	ProviderKey string `protobuf:"bytes,2,opt,name=providerKey,proto3" json:"providerKey,omitempty"`
	KeyName     string `protobuf:"bytes,3,opt,name=keyName,proto3" json:"keyName,omitempty"`
}

func (x *CreateProviderCredentialRequest) Reset() {
	*x = CreateProviderCredentialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProviderCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderCredentialRequest) ProtoMessage() {}

func (x *CreateProviderCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderCredentialRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderCredentialRequest) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProviderCredentialRequest) GetProviderId() uint64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *CreateProviderCredentialRequest) GetProviderKey() string {
	if x != nil {
		return x.ProviderKey
	}
	return ""
}

func (x *CreateProviderCredentialRequest) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

type CreateProviderCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Success bool                `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Data    *ProviderCredential `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateProviderCredentialResponse) Reset() {
	*x = CreateProviderCredentialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProviderCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderCredentialResponse) ProtoMessage() {}

func (x *CreateProviderCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderCredentialResponse.ProtoReflect.Descriptor instead.
func (*CreateProviderCredentialResponse) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProviderCredentialResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateProviderCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateProviderCredentialResponse) GetData() *ProviderCredential {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteProviderCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderKeyId uint64 `protobuf:"varint,1,opt,name=providerKeyId,proto3" json:"providerKeyId,omitempty"`
}

func (x *DeleteProviderCredentialRequest) Reset() {
	*x = DeleteProviderCredentialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProviderCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderCredentialRequest) ProtoMessage() {}

func (x *DeleteProviderCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteProviderCredentialRequest) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteProviderCredentialRequest) GetProviderKeyId() uint64 {
	if x != nil {
		return x.ProviderKeyId
	}
	return 0
}

type DeleteProviderCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Id      uint64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteProviderCredentialResponse) Reset() {
	*x = DeleteProviderCredentialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProviderCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderCredentialResponse) ProtoMessage() {}

func (x *DeleteProviderCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteProviderCredentialResponse) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProviderCredentialResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteProviderCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteProviderCredentialResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllProviderCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Success bool                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Data    []*ProviderCredential `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllProviderCredentialResponse) Reset() {
	*x = GetAllProviderCredentialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllProviderCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProviderCredentialResponse) ProtoMessage() {}

func (x *GetAllProviderCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProviderCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetAllProviderCredentialResponse) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllProviderCredentialResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAllProviderCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllProviderCredentialResponse) GetData() []*ProviderCredential {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetProviderCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderId     uint64 `protobuf:"varint,3,opt,name=providerId,proto3" json:"providerId,omitempty"`
	OrganizationId uint64 `protobuf:"varint,4,opt,name=organizationId,proto3" json:"organizationId,omitempty"`
}

func (x *GetProviderCredentialRequest) Reset() {
	*x = GetProviderCredentialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProviderCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderCredentialRequest) ProtoMessage() {}

func (x *GetProviderCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetProviderCredentialRequest) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetProviderCredentialRequest) GetProviderId() uint64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *GetProviderCredentialRequest) GetOrganizationId() uint64 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

type GetProviderCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Key     string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Id      uint64 `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProviderCredentialResponse) Reset() {
	*x = GetProviderCredentialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProviderCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderCredentialResponse) ProtoMessage() {}

func (x *GetProviderCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetProviderCredentialResponse) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetProviderCredentialResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetProviderCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetProviderCredentialResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProviderCredentialResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetProviderCredentialResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllProviderCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mask *bool `protobuf:"varint,1,opt,name=mask,proto3,oneof" json:"mask,omitempty"`
}

func (x *GetAllProviderCredentialRequest) Reset() {
	*x = GetAllProviderCredentialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllProviderCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProviderCredentialRequest) ProtoMessage() {}

func (x *GetAllProviderCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProviderCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetAllProviderCredentialRequest) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllProviderCredentialRequest) GetMask() bool {
	if x != nil && x.Mask != nil {
		return *x.Mask
	}
	return false
}

type UpdateVaultCredentialsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId uint64 `protobuf:"varint,2,opt,name=providerId,proto3" json:"providerId,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Key        string `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *UpdateVaultCredentialsRequest) Reset() {
	*x = UpdateVaultCredentialsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVaultCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVaultCredentialsRequest) ProtoMessage() {}

func (x *UpdateVaultCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVaultCredentialsRequest.ProtoReflect.Descriptor instead.
func (*UpdateVaultCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateVaultCredentialsRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVaultCredentialsRequest) GetProviderId() uint64 {
	if x != nil {
		return x.ProviderId
	}
	return 0
}

func (x *UpdateVaultCredentialsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateVaultCredentialsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UpdateVaultCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Success bool                `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Data    *ProviderCredential `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateVaultCredentialResponse) Reset() {
	*x = UpdateVaultCredentialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateVaultCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVaultCredentialResponse) ProtoMessage() {}

func (x *UpdateVaultCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVaultCredentialResponse.ProtoReflect.Descriptor instead.
func (*UpdateVaultCredentialResponse) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateVaultCredentialResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateVaultCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateVaultCredentialResponse) GetData() *ProviderCredential {
	if x != nil {
		return x.Data
	}
	return nil
}

type RollScopeCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyType string `protobuf:"bytes,1,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
}

func (x *RollScopeCredentialRequest) Reset() {
	*x = RollScopeCredentialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollScopeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollScopeCredentialRequest) ProtoMessage() {}

func (x *RollScopeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollScopeCredentialRequest.ProtoReflect.Descriptor instead.
func (*RollScopeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{11}
}

func (x *RollScopeCredentialRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type RollScopeCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RollScopeCredentialResponse) Reset() {
	*x = RollScopeCredentialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollScopeCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollScopeCredentialResponse) ProtoMessage() {}

func (x *RollScopeCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollScopeCredentialResponse.ProtoReflect.Descriptor instead.
func (*RollScopeCredentialResponse) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{12}
}

type AddIpRestrictionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddIpRestrictionRequest) Reset() {
	*x = AddIpRestrictionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddIpRestrictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIpRestrictionRequest) ProtoMessage() {}

func (x *AddIpRestrictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIpRestrictionRequest.ProtoReflect.Descriptor instead.
func (*AddIpRestrictionRequest) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{13}
}

type AddIpRestrictionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddIpRestrictionResponse) Reset() {
	*x = AddIpRestrictionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddIpRestrictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIpRestrictionResponse) ProtoMessage() {}

func (x *AddIpRestrictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIpRestrictionResponse.ProtoReflect.Descriptor instead.
func (*AddIpRestrictionResponse) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{14}
}

type DeleteIpRestrictionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteIpRestrictionRequest) Reset() {
	*x = DeleteIpRestrictionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIpRestrictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIpRestrictionRequest) ProtoMessage() {}

func (x *DeleteIpRestrictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIpRestrictionRequest.ProtoReflect.Descriptor instead.
func (*DeleteIpRestrictionRequest) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{15}
}

type DeleteIpRestrictionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteIpRestrictionResponse) Reset() {
	*x = DeleteIpRestrictionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIpRestrictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIpRestrictionResponse) ProtoMessage() {}

func (x *DeleteIpRestrictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIpRestrictionResponse.ProtoReflect.Descriptor instead.
func (*DeleteIpRestrictionResponse) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{16}
}

type ScopeCredential struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScopeCredential) Reset() {
	*x = ScopeCredential{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScopeCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeCredential) ProtoMessage() {}

func (x *ScopeCredential) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeCredential.ProtoReflect.Descriptor instead.
func (*ScopeCredential) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{17}
}

type GetScopeCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Success bool             `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Data    *ScopeCredential `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetScopeCredentialResponse) Reset() {
	*x = GetScopeCredentialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lexatic_backend_vault_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScopeCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScopeCredentialResponse) ProtoMessage() {}

func (x *GetScopeCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lexatic_backend_vault_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScopeCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetScopeCredentialResponse) Descriptor() ([]byte, []int) {
	return file_lexatic_backend_vault_api_proto_rawDescGZIP(), []int{18}
}

func (x *GetScopeCredentialResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetScopeCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetScopeCredentialResponse) GetData() *ScopeCredential {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_lexatic_backend_vault_api_proto protoreflect.FileDescriptor

var file_lexatic_backend_vault_api_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6c, 0x65, 0x78, 0x61, 0x74, 0x69, 0x63, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x02, 0x0a, 0x12, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x12, 0x12, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30,
	0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30, 0x01, 0x52, 0x0a, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x0e, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x42, 0x02, 0x30, 0x01, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30, 0x01, 0x52,
	0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x6b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a,
	0x1f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30, 0x01, 0x52, 0x0d, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x20, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30, 0x01, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x83, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30, 0x01, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x0e, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x42, 0x02, 0x30, 0x01, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x30, 0x01, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x43, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x22, 0x7d, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56,
	0x61, 0x75, 0x6c, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x42, 0x02, 0x30, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02,
	0x30, 0x01, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x80, 0x01, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56,
	0x61, 0x75, 0x6c, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x36, 0x0a, 0x1a, 0x52, 0x6f, 0x6c, 0x6c, 0x53,
	0x63, 0x6f, 0x70, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x1d, 0x0a, 0x1b, 0x52, 0x6f, 0x6c, 0x6c, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19,
	0x0a, 0x17, 0x41, 0x64, 0x64, 0x49, 0x70, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x41, 0x64, 0x64,
	0x49, 0x70, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49,
	0x70, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x70, 0x52,
	0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x7a, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0xc7, 0x04, 0x0a, 0x0c, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x73, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x2a,
	0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x12, 0x2a, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x2a, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x27, 0x2e, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x28, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x89, 0x04, 0x0a, 0x16,
	0x53, 0x63, 0x6f, 0x70, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x1c, 0x52, 0x6f, 0x6c, 0x6c, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x25, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x53, 0x63,
	0x6f, 0x70, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x17, 0x52, 0x6f, 0x6c, 0x6c, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x12, 0x25, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x6c,
	0x6c, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5b, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x49, 0x70, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x64, 0x64, 0x49, 0x70, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x70, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x70, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x70, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x70, 0x52,
	0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x25, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x63, 0x6f, 0x70, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x78, 0x61, 0x74, 0x69, 0x63, 0x2f, 0x77, 0x65,
	0x62, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x6c, 0x65, 0x78, 0x61, 0x74, 0x69, 0x63, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lexatic_backend_vault_api_proto_rawDescOnce sync.Once
	file_lexatic_backend_vault_api_proto_rawDescData = file_lexatic_backend_vault_api_proto_rawDesc
)

func file_lexatic_backend_vault_api_proto_rawDescGZIP() []byte {
	file_lexatic_backend_vault_api_proto_rawDescOnce.Do(func() {
		file_lexatic_backend_vault_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_lexatic_backend_vault_api_proto_rawDescData)
	})
	return file_lexatic_backend_vault_api_proto_rawDescData
}

var file_lexatic_backend_vault_api_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_lexatic_backend_vault_api_proto_goTypes = []interface{}{
	(*ProviderCredential)(nil),               // 0: vault_api.ProviderCredential
	(*CreateProviderCredentialRequest)(nil),  // 1: vault_api.CreateProviderCredentialRequest
	(*CreateProviderCredentialResponse)(nil), // 2: vault_api.CreateProviderCredentialResponse
	(*DeleteProviderCredentialRequest)(nil),  // 3: vault_api.DeleteProviderCredentialRequest
	(*DeleteProviderCredentialResponse)(nil), // 4: vault_api.DeleteProviderCredentialResponse
	(*GetAllProviderCredentialResponse)(nil), // 5: vault_api.GetAllProviderCredentialResponse
	(*GetProviderCredentialRequest)(nil),     // 6: vault_api.GetProviderCredentialRequest
	(*GetProviderCredentialResponse)(nil),    // 7: vault_api.GetProviderCredentialResponse
	(*GetAllProviderCredentialRequest)(nil),  // 8: vault_api.GetAllProviderCredentialRequest
	(*UpdateVaultCredentialsRequest)(nil),    // 9: vault_api.UpdateVaultCredentialsRequest
	(*UpdateVaultCredentialResponse)(nil),    // 10: vault_api.UpdateVaultCredentialResponse
	(*RollScopeCredentialRequest)(nil),       // 11: vault_api.RollScopeCredentialRequest
	(*RollScopeCredentialResponse)(nil),      // 12: vault_api.RollScopeCredentialResponse
	(*AddIpRestrictionRequest)(nil),          // 13: vault_api.AddIpRestrictionRequest
	(*AddIpRestrictionResponse)(nil),         // 14: vault_api.AddIpRestrictionResponse
	(*DeleteIpRestrictionRequest)(nil),       // 15: vault_api.DeleteIpRestrictionRequest
	(*DeleteIpRestrictionResponse)(nil),      // 16: vault_api.DeleteIpRestrictionResponse
	(*ScopeCredential)(nil),                  // 17: vault_api.ScopeCredential
	(*GetScopeCredentialResponse)(nil),       // 18: vault_api.GetScopeCredentialResponse
	(*timestamppb.Timestamp)(nil),            // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 20: google.protobuf.Empty
}
var file_lexatic_backend_vault_api_proto_depIdxs = []int32{
	19, // 0: vault_api.ProviderCredential.createdDate:type_name -> google.protobuf.Timestamp
	0,  // 1: vault_api.CreateProviderCredentialResponse.data:type_name -> vault_api.ProviderCredential
	0,  // 2: vault_api.GetAllProviderCredentialResponse.data:type_name -> vault_api.ProviderCredential
	0,  // 3: vault_api.UpdateVaultCredentialResponse.data:type_name -> vault_api.ProviderCredential
	17, // 4: vault_api.GetScopeCredentialResponse.data:type_name -> vault_api.ScopeCredential
	1,  // 5: vault_api.VaultService.CreateProviderCredential:input_type -> vault_api.CreateProviderCredentialRequest
	3,  // 6: vault_api.VaultService.DeleteProviderCredential:input_type -> vault_api.DeleteProviderCredentialRequest
	8,  // 7: vault_api.VaultService.GetAllProviderCredential:input_type -> vault_api.GetAllProviderCredentialRequest
	6,  // 8: vault_api.VaultService.GetProviderCredential:input_type -> vault_api.GetProviderCredentialRequest
	9,  // 9: vault_api.VaultService.UpdateVaultCredentials:input_type -> vault_api.UpdateVaultCredentialsRequest
	11, // 10: vault_api.ScopeCredentialService.RollPublishableKeyCredential:input_type -> vault_api.RollScopeCredentialRequest
	11, // 11: vault_api.ScopeCredentialService.RollSecretKeyCredential:input_type -> vault_api.RollScopeCredentialRequest
	13, // 12: vault_api.ScopeCredentialService.AddIpRestriction:input_type -> vault_api.AddIpRestrictionRequest
	15, // 13: vault_api.ScopeCredentialService.DeleteIpRestriction:input_type -> vault_api.DeleteIpRestrictionRequest
	20, // 14: vault_api.ScopeCredentialService.GetScopeCredential:input_type -> google.protobuf.Empty
	2,  // 15: vault_api.VaultService.CreateProviderCredential:output_type -> vault_api.CreateProviderCredentialResponse
	4,  // 16: vault_api.VaultService.DeleteProviderCredential:output_type -> vault_api.DeleteProviderCredentialResponse
	5,  // 17: vault_api.VaultService.GetAllProviderCredential:output_type -> vault_api.GetAllProviderCredentialResponse
	7,  // 18: vault_api.VaultService.GetProviderCredential:output_type -> vault_api.GetProviderCredentialResponse
	10, // 19: vault_api.VaultService.UpdateVaultCredentials:output_type -> vault_api.UpdateVaultCredentialResponse
	12, // 20: vault_api.ScopeCredentialService.RollPublishableKeyCredential:output_type -> vault_api.RollScopeCredentialResponse
	12, // 21: vault_api.ScopeCredentialService.RollSecretKeyCredential:output_type -> vault_api.RollScopeCredentialResponse
	14, // 22: vault_api.ScopeCredentialService.AddIpRestriction:output_type -> vault_api.AddIpRestrictionResponse
	16, // 23: vault_api.ScopeCredentialService.DeleteIpRestriction:output_type -> vault_api.DeleteIpRestrictionResponse
	18, // 24: vault_api.ScopeCredentialService.GetScopeCredential:output_type -> vault_api.GetScopeCredentialResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_lexatic_backend_vault_api_proto_init() }
func file_lexatic_backend_vault_api_proto_init() {
	if File_lexatic_backend_vault_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lexatic_backend_vault_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderCredential); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProviderCredentialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProviderCredentialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProviderCredentialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProviderCredentialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllProviderCredentialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProviderCredentialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProviderCredentialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllProviderCredentialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVaultCredentialsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateVaultCredentialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollScopeCredentialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollScopeCredentialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddIpRestrictionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddIpRestrictionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIpRestrictionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIpRestrictionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScopeCredential); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lexatic_backend_vault_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScopeCredentialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lexatic_backend_vault_api_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lexatic_backend_vault_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_lexatic_backend_vault_api_proto_goTypes,
		DependencyIndexes: file_lexatic_backend_vault_api_proto_depIdxs,
		MessageInfos:      file_lexatic_backend_vault_api_proto_msgTypes,
	}.Build()
	File_lexatic_backend_vault_api_proto = out.File
	file_lexatic_backend_vault_api_proto_rawDesc = nil
	file_lexatic_backend_vault_api_proto_goTypes = nil
	file_lexatic_backend_vault_api_proto_depIdxs = nil
}
