// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: lexatic-backend/vault-api.proto

package lexatic_backend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VaultService_CreateProviderCredential_FullMethodName = "/vault_api.VaultService/CreateProviderCredential"
	VaultService_DeleteProviderCredential_FullMethodName = "/vault_api.VaultService/DeleteProviderCredential"
	VaultService_GetAllProviderCredential_FullMethodName = "/vault_api.VaultService/GetAllProviderCredential"
	VaultService_GetProviderCredential_FullMethodName    = "/vault_api.VaultService/GetProviderCredential"
	VaultService_UpdateVaultCredentials_FullMethodName   = "/vault_api.VaultService/UpdateVaultCredentials"
)

// VaultServiceClient is the client API for VaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VaultServiceClient interface {
	CreateProviderCredential(ctx context.Context, in *CreateProviderCredentialRequest, opts ...grpc.CallOption) (*CreateProviderCredentialResponse, error)
	DeleteProviderCredential(ctx context.Context, in *DeleteProviderCredentialRequest, opts ...grpc.CallOption) (*DeleteProviderCredentialResponse, error)
	GetAllProviderCredential(ctx context.Context, in *GetAllProviderCredentialRequest, opts ...grpc.CallOption) (*GetAllProviderCredentialResponse, error)
	GetProviderCredential(ctx context.Context, in *GetProviderCredentialRequest, opts ...grpc.CallOption) (*GetProviderCredentialResponse, error)
	UpdateVaultCredentials(ctx context.Context, in *UpdateVaultCredentialsRequest, opts ...grpc.CallOption) (*UpdateVaultCredentialResponse, error)
}

type vaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVaultServiceClient(cc grpc.ClientConnInterface) VaultServiceClient {
	return &vaultServiceClient{cc}
}

func (c *vaultServiceClient) CreateProviderCredential(ctx context.Context, in *CreateProviderCredentialRequest, opts ...grpc.CallOption) (*CreateProviderCredentialResponse, error) {
	out := new(CreateProviderCredentialResponse)
	err := c.cc.Invoke(ctx, VaultService_CreateProviderCredential_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) DeleteProviderCredential(ctx context.Context, in *DeleteProviderCredentialRequest, opts ...grpc.CallOption) (*DeleteProviderCredentialResponse, error) {
	out := new(DeleteProviderCredentialResponse)
	err := c.cc.Invoke(ctx, VaultService_DeleteProviderCredential_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) GetAllProviderCredential(ctx context.Context, in *GetAllProviderCredentialRequest, opts ...grpc.CallOption) (*GetAllProviderCredentialResponse, error) {
	out := new(GetAllProviderCredentialResponse)
	err := c.cc.Invoke(ctx, VaultService_GetAllProviderCredential_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) GetProviderCredential(ctx context.Context, in *GetProviderCredentialRequest, opts ...grpc.CallOption) (*GetProviderCredentialResponse, error) {
	out := new(GetProviderCredentialResponse)
	err := c.cc.Invoke(ctx, VaultService_GetProviderCredential_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) UpdateVaultCredentials(ctx context.Context, in *UpdateVaultCredentialsRequest, opts ...grpc.CallOption) (*UpdateVaultCredentialResponse, error) {
	out := new(UpdateVaultCredentialResponse)
	err := c.cc.Invoke(ctx, VaultService_UpdateVaultCredentials_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultServiceServer is the server API for VaultService service.
// All implementations should embed UnimplementedVaultServiceServer
// for forward compatibility
type VaultServiceServer interface {
	CreateProviderCredential(context.Context, *CreateProviderCredentialRequest) (*CreateProviderCredentialResponse, error)
	DeleteProviderCredential(context.Context, *DeleteProviderCredentialRequest) (*DeleteProviderCredentialResponse, error)
	GetAllProviderCredential(context.Context, *GetAllProviderCredentialRequest) (*GetAllProviderCredentialResponse, error)
	GetProviderCredential(context.Context, *GetProviderCredentialRequest) (*GetProviderCredentialResponse, error)
	UpdateVaultCredentials(context.Context, *UpdateVaultCredentialsRequest) (*UpdateVaultCredentialResponse, error)
}

// UnimplementedVaultServiceServer should be embedded to have forward compatible implementations.
type UnimplementedVaultServiceServer struct {
}

func (UnimplementedVaultServiceServer) CreateProviderCredential(context.Context, *CreateProviderCredentialRequest) (*CreateProviderCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProviderCredential not implemented")
}
func (UnimplementedVaultServiceServer) DeleteProviderCredential(context.Context, *DeleteProviderCredentialRequest) (*DeleteProviderCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProviderCredential not implemented")
}
func (UnimplementedVaultServiceServer) GetAllProviderCredential(context.Context, *GetAllProviderCredentialRequest) (*GetAllProviderCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllProviderCredential not implemented")
}
func (UnimplementedVaultServiceServer) GetProviderCredential(context.Context, *GetProviderCredentialRequest) (*GetProviderCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderCredential not implemented")
}
func (UnimplementedVaultServiceServer) UpdateVaultCredentials(context.Context, *UpdateVaultCredentialsRequest) (*UpdateVaultCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVaultCredentials not implemented")
}

// UnsafeVaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaultServiceServer will
// result in compilation errors.
type UnsafeVaultServiceServer interface {
	mustEmbedUnimplementedVaultServiceServer()
}

func RegisterVaultServiceServer(s grpc.ServiceRegistrar, srv VaultServiceServer) {
	s.RegisterService(&VaultService_ServiceDesc, srv)
}

func _VaultService_CreateProviderCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).CreateProviderCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_CreateProviderCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).CreateProviderCredential(ctx, req.(*CreateProviderCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_DeleteProviderCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProviderCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).DeleteProviderCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_DeleteProviderCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).DeleteProviderCredential(ctx, req.(*DeleteProviderCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_GetAllProviderCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProviderCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).GetAllProviderCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_GetAllProviderCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).GetAllProviderCredential(ctx, req.(*GetAllProviderCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_GetProviderCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).GetProviderCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_GetProviderCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).GetProviderCredential(ctx, req.(*GetProviderCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_UpdateVaultCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVaultCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).UpdateVaultCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_UpdateVaultCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).UpdateVaultCredentials(ctx, req.(*UpdateVaultCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VaultService_ServiceDesc is the grpc.ServiceDesc for VaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vault_api.VaultService",
	HandlerType: (*VaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProviderCredential",
			Handler:    _VaultService_CreateProviderCredential_Handler,
		},
		{
			MethodName: "DeleteProviderCredential",
			Handler:    _VaultService_DeleteProviderCredential_Handler,
		},
		{
			MethodName: "GetAllProviderCredential",
			Handler:    _VaultService_GetAllProviderCredential_Handler,
		},
		{
			MethodName: "GetProviderCredential",
			Handler:    _VaultService_GetProviderCredential_Handler,
		},
		{
			MethodName: "UpdateVaultCredentials",
			Handler:    _VaultService_UpdateVaultCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lexatic-backend/vault-api.proto",
}

const (
	ScopeCredentialService_RollPublishableKeyCredential_FullMethodName = "/vault_api.ScopeCredentialService/RollPublishableKeyCredential"
	ScopeCredentialService_RollSecretKeyCredential_FullMethodName      = "/vault_api.ScopeCredentialService/RollSecretKeyCredential"
	ScopeCredentialService_AddIpRestriction_FullMethodName             = "/vault_api.ScopeCredentialService/AddIpRestriction"
	ScopeCredentialService_DeleteIpRestriction_FullMethodName          = "/vault_api.ScopeCredentialService/DeleteIpRestriction"
	ScopeCredentialService_GetScopeCredential_FullMethodName           = "/vault_api.ScopeCredentialService/GetScopeCredential"
)

// ScopeCredentialServiceClient is the client API for ScopeCredentialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScopeCredentialServiceClient interface {
	RollPublishableKeyCredential(ctx context.Context, in *RollScopeCredentialRequest, opts ...grpc.CallOption) (*RollScopeCredentialResponse, error)
	RollSecretKeyCredential(ctx context.Context, in *RollScopeCredentialRequest, opts ...grpc.CallOption) (*RollScopeCredentialResponse, error)
	AddIpRestriction(ctx context.Context, in *AddIpRestrictionRequest, opts ...grpc.CallOption) (*AddIpRestrictionResponse, error)
	DeleteIpRestriction(ctx context.Context, in *DeleteIpRestrictionRequest, opts ...grpc.CallOption) (*DeleteIpRestrictionResponse, error)
	GetScopeCredential(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetScopeCredentialResponse, error)
}

type scopeCredentialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScopeCredentialServiceClient(cc grpc.ClientConnInterface) ScopeCredentialServiceClient {
	return &scopeCredentialServiceClient{cc}
}

func (c *scopeCredentialServiceClient) RollPublishableKeyCredential(ctx context.Context, in *RollScopeCredentialRequest, opts ...grpc.CallOption) (*RollScopeCredentialResponse, error) {
	out := new(RollScopeCredentialResponse)
	err := c.cc.Invoke(ctx, ScopeCredentialService_RollPublishableKeyCredential_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scopeCredentialServiceClient) RollSecretKeyCredential(ctx context.Context, in *RollScopeCredentialRequest, opts ...grpc.CallOption) (*RollScopeCredentialResponse, error) {
	out := new(RollScopeCredentialResponse)
	err := c.cc.Invoke(ctx, ScopeCredentialService_RollSecretKeyCredential_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scopeCredentialServiceClient) AddIpRestriction(ctx context.Context, in *AddIpRestrictionRequest, opts ...grpc.CallOption) (*AddIpRestrictionResponse, error) {
	out := new(AddIpRestrictionResponse)
	err := c.cc.Invoke(ctx, ScopeCredentialService_AddIpRestriction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scopeCredentialServiceClient) DeleteIpRestriction(ctx context.Context, in *DeleteIpRestrictionRequest, opts ...grpc.CallOption) (*DeleteIpRestrictionResponse, error) {
	out := new(DeleteIpRestrictionResponse)
	err := c.cc.Invoke(ctx, ScopeCredentialService_DeleteIpRestriction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scopeCredentialServiceClient) GetScopeCredential(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetScopeCredentialResponse, error) {
	out := new(GetScopeCredentialResponse)
	err := c.cc.Invoke(ctx, ScopeCredentialService_GetScopeCredential_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScopeCredentialServiceServer is the server API for ScopeCredentialService service.
// All implementations should embed UnimplementedScopeCredentialServiceServer
// for forward compatibility
type ScopeCredentialServiceServer interface {
	RollPublishableKeyCredential(context.Context, *RollScopeCredentialRequest) (*RollScopeCredentialResponse, error)
	RollSecretKeyCredential(context.Context, *RollScopeCredentialRequest) (*RollScopeCredentialResponse, error)
	AddIpRestriction(context.Context, *AddIpRestrictionRequest) (*AddIpRestrictionResponse, error)
	DeleteIpRestriction(context.Context, *DeleteIpRestrictionRequest) (*DeleteIpRestrictionResponse, error)
	GetScopeCredential(context.Context, *emptypb.Empty) (*GetScopeCredentialResponse, error)
}

// UnimplementedScopeCredentialServiceServer should be embedded to have forward compatible implementations.
type UnimplementedScopeCredentialServiceServer struct {
}

func (UnimplementedScopeCredentialServiceServer) RollPublishableKeyCredential(context.Context, *RollScopeCredentialRequest) (*RollScopeCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollPublishableKeyCredential not implemented")
}
func (UnimplementedScopeCredentialServiceServer) RollSecretKeyCredential(context.Context, *RollScopeCredentialRequest) (*RollScopeCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollSecretKeyCredential not implemented")
}
func (UnimplementedScopeCredentialServiceServer) AddIpRestriction(context.Context, *AddIpRestrictionRequest) (*AddIpRestrictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIpRestriction not implemented")
}
func (UnimplementedScopeCredentialServiceServer) DeleteIpRestriction(context.Context, *DeleteIpRestrictionRequest) (*DeleteIpRestrictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIpRestriction not implemented")
}
func (UnimplementedScopeCredentialServiceServer) GetScopeCredential(context.Context, *emptypb.Empty) (*GetScopeCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScopeCredential not implemented")
}

// UnsafeScopeCredentialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScopeCredentialServiceServer will
// result in compilation errors.
type UnsafeScopeCredentialServiceServer interface {
	mustEmbedUnimplementedScopeCredentialServiceServer()
}

func RegisterScopeCredentialServiceServer(s grpc.ServiceRegistrar, srv ScopeCredentialServiceServer) {
	s.RegisterService(&ScopeCredentialService_ServiceDesc, srv)
}

func _ScopeCredentialService_RollPublishableKeyCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollScopeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeCredentialServiceServer).RollPublishableKeyCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeCredentialService_RollPublishableKeyCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeCredentialServiceServer).RollPublishableKeyCredential(ctx, req.(*RollScopeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScopeCredentialService_RollSecretKeyCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollScopeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeCredentialServiceServer).RollSecretKeyCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeCredentialService_RollSecretKeyCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeCredentialServiceServer).RollSecretKeyCredential(ctx, req.(*RollScopeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScopeCredentialService_AddIpRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIpRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeCredentialServiceServer).AddIpRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeCredentialService_AddIpRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeCredentialServiceServer).AddIpRestriction(ctx, req.(*AddIpRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScopeCredentialService_DeleteIpRestriction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIpRestrictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeCredentialServiceServer).DeleteIpRestriction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeCredentialService_DeleteIpRestriction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeCredentialServiceServer).DeleteIpRestriction(ctx, req.(*DeleteIpRestrictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScopeCredentialService_GetScopeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeCredentialServiceServer).GetScopeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeCredentialService_GetScopeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeCredentialServiceServer).GetScopeCredential(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ScopeCredentialService_ServiceDesc is the grpc.ServiceDesc for ScopeCredentialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScopeCredentialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vault_api.ScopeCredentialService",
	HandlerType: (*ScopeCredentialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RollPublishableKeyCredential",
			Handler:    _ScopeCredentialService_RollPublishableKeyCredential_Handler,
		},
		{
			MethodName: "RollSecretKeyCredential",
			Handler:    _ScopeCredentialService_RollSecretKeyCredential_Handler,
		},
		{
			MethodName: "AddIpRestriction",
			Handler:    _ScopeCredentialService_AddIpRestriction_Handler,
		},
		{
			MethodName: "DeleteIpRestriction",
			Handler:    _ScopeCredentialService_DeleteIpRestriction_Handler,
		},
		{
			MethodName: "GetScopeCredential",
			Handler:    _ScopeCredentialService_GetScopeCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lexatic-backend/vault-api.proto",
}
