version: "2"

run:
  timeout: 10m

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - errorlint
    - gosec
    - revive
  disable:
    - wrapcheck
    - exhaustruct
    - ireturn
    - varnamelen
    - depguard
    - paralleltest
    - funlen
    - gocognit
    - cyclop
    - lll
    - nlreturn
    - wsl
    - godot
    - godox
    - gochecknoglobals
    - gochecknoinits
    - testpackage
    - dupl
    - tagliatelle
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
    paths:
      - protos/.*\.pb\.go$
      - protos/.*_grpc\.pb\.go$
      - vendor/
      - api/assistant-api/internal/vad/silero_vad/.*
      - api/assistant-api/internal/vad/ten_vad/.*
      - api/assistant-api/internal/denoiser/.*
    rules:
      - path: _test\.go
        linters: [errcheck, gosec, bodyclose]
      - path: cmd/
        text: "use of `fmt.Print"
        linters: [forbidigo]
      - path: config/
        linters: [funlen]

settings:
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: var-naming
        disabled: true
      - name: dot-imports
        disabled: true
  gosec:
    excludes: [G104, G304, G401, G501, G505]
  errorlint:
    errorf: true
    asserts: true
    comparison: true

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/rapidaai

output:
  formats:
    colored-line-number: {}
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

severity:
  default: warning
  rules:
    - linters: [errcheck, gosec]
      severity: error
