#!/usr/bin/env bash
# start templated
INSTALL_PYTHON=$(which python3)
if [ -z "$INSTALL_PYTHON" ]; then echo "please install python3 to setup the pre-commit hooks."; exit; fi
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated
HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v $(pwd)/bin/pre-commit > /dev/null; then
    exec $(pwd)/bin/pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Are you running from project root folder?' 1>&2
    exit 1
fi
