// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"
)

// Assistant defines model for Assistant.
type Assistant struct {
	AssistantKnowledges        *[]AssistantKnowledge       `json:"assistantKnowledges,omitempty"`
	AssistantProvider          *string                     `json:"assistantProvider,omitempty"`
	AssistantProviderAgentflow *AssistantProviderAgentflow `json:"assistantProviderAgentflow,omitempty"`
	AssistantProviderAgentkit  *AssistantProviderAgentkit  `json:"assistantProviderAgentkit,omitempty"`
	AssistantProviderId        *Uint64String               `json:"assistantProviderId,omitempty"`
	AssistantProviderModel     *AssistantProviderModel     `json:"assistantProviderModel,omitempty"`
	AssistantProviderWebsocket *AssistantProviderWebsocket `json:"assistantProviderWebsocket,omitempty"`
	AssistantTag               *AssistantTag               `json:"assistantTag,omitempty"`
	AssistantTools             *[]AssistantTool            `json:"assistantTools,omitempty"`
	CreatedBy                  *Uint64String               `json:"createdBy,omitempty"`
	CreatedDate                *time.Time                  `json:"createdDate,omitempty"`
	Description                *string                     `json:"description,omitempty"`
	Id                         *Uint64String               `json:"id,omitempty"`
	Name                       *string                     `json:"name,omitempty"`
	OrganizationId             *Uint64String               `json:"organizationId,omitempty"`
	ProjectId                  *Uint64String               `json:"projectId,omitempty"`
	Source                     *string                     `json:"source,omitempty"`
	SourceIdentifier           *Uint64String               `json:"sourceIdentifier,omitempty"`
	Status                     *string                     `json:"status,omitempty"`
	UpdatedBy                  *Uint64String               `json:"updatedBy,omitempty"`
	UpdatedDate                *time.Time                  `json:"updatedDate,omitempty"`
	Visibility                 *string                     `json:"visibility,omitempty"`
}

// AssistantApiDeployment defines model for AssistantApiDeployment.
type AssistantApiDeployment struct {
	AssistantId           *Uint64String            `json:"assistantId,omitempty"`
	Greeting              *string                  `json:"greeting,omitempty"`
	GreetingInterruptible *bool                    `json:"greetingInterruptible,omitempty"`
	Id                    *Uint64String            `json:"id,omitempty"`
	IdealTimeout          *uint64                  `json:"idealTimeout,omitempty"`
	IdealTimeoutBackoff   *uint64                  `json:"idealTimeoutBackoff,omitempty"`
	IdealTimeoutMessage   *string                  `json:"idealTimeoutMessage,omitempty"`
	InputAudio            *DeploymentAudioProvider `json:"inputAudio,omitempty"`
	MaxSessionDuration    *uint64                  `json:"maxSessionDuration,omitempty"`
	Mistake               *string                  `json:"mistake,omitempty"`
	OutputAudio           *DeploymentAudioProvider `json:"outputAudio,omitempty"`
	Status                *string                  `json:"status,omitempty"`
	UnclearInputMessage   *string                  `json:"unclearInputMessage,omitempty"`
	UnclearInputTimeout   *float64                 `json:"unclearInputTimeout,omitempty"`
}

// AssistantConfiguration defines model for AssistantConfiguration.
type AssistantConfiguration struct {
	AssistantId       *Uint64String `json:"assistantId,omitempty"`
	ConfigurationType *string       `json:"configurationType,omitempty"`
	CreatedBy         *Uint64String `json:"createdBy,omitempty"`
	CreatedDate       *time.Time    `json:"createdDate,omitempty"`
	Enabled           *bool         `json:"enabled,omitempty"`
	Id                *Uint64String `json:"id,omitempty"`
	Options           *[]Metadata   `json:"options,omitempty"`
	OrganizationId    *Uint64String `json:"organizationId,omitempty"`
	ProjectId         *Uint64String `json:"projectId,omitempty"`
	Provider          *string       `json:"provider,omitempty"`
	Status            *string       `json:"status,omitempty"`
	UpdatedBy         *Uint64String `json:"updatedBy,omitempty"`
	UpdatedDate       *time.Time    `json:"updatedDate,omitempty"`
}

// AssistantDebuggerDeployment defines model for AssistantDebuggerDeployment.
type AssistantDebuggerDeployment struct {
	AssistantId           *Uint64String            `json:"assistantId,omitempty"`
	Greeting              *string                  `json:"greeting,omitempty"`
	GreetingInterruptible *bool                    `json:"greetingInterruptible,omitempty"`
	Id                    *Uint64String            `json:"id,omitempty"`
	IdealTimeout          *uint64                  `json:"idealTimeout,omitempty"`
	IdealTimeoutBackoff   *uint64                  `json:"idealTimeoutBackoff,omitempty"`
	IdealTimeoutMessage   *string                  `json:"idealTimeoutMessage,omitempty"`
	InputAudio            *DeploymentAudioProvider `json:"inputAudio,omitempty"`
	MaxSessionDuration    *uint64                  `json:"maxSessionDuration,omitempty"`
	Mistake               *string                  `json:"mistake,omitempty"`
	OutputAudio           *DeploymentAudioProvider `json:"outputAudio,omitempty"`
	Status                *string                  `json:"status,omitempty"`
	UnclearInputMessage   *string                  `json:"unclearInputMessage,omitempty"`
	UnclearInputTimeout   *float64                 `json:"unclearInputTimeout,omitempty"`
}

// AssistantKnowledge defines model for AssistantKnowledge.
type AssistantKnowledge struct {
	AssistantKnowledgeRerankerOptions *[]Metadata   `json:"assistantKnowledgeRerankerOptions,omitempty"`
	Id                                *Uint64String `json:"id,omitempty"`
	KnowledgeId                       *Uint64String `json:"knowledgeId,omitempty"`
	RerankerEnable                    *bool         `json:"rerankerEnable,omitempty"`
	RerankerModelProviderId           *Uint64String `json:"rerankerModelProviderId,omitempty"`
	RerankerModelProviderName         *string       `json:"rerankerModelProviderName,omitempty"`
	RetrievalMethod                   *string       `json:"retrievalMethod,omitempty"`
	ScoreThreshold                    *float32      `json:"scoreThreshold,omitempty"`
	Status                            *string       `json:"status,omitempty"`
	TopK                              *uint32       `json:"topK,omitempty"`
}

// AssistantPhoneDeployment defines model for AssistantPhoneDeployment.
type AssistantPhoneDeployment struct {
	AssistantId           *Uint64String            `json:"assistantId,omitempty"`
	Greeting              *string                  `json:"greeting,omitempty"`
	GreetingInterruptible *bool                    `json:"greetingInterruptible,omitempty"`
	Id                    *Uint64String            `json:"id,omitempty"`
	IdealTimeout          *uint64                  `json:"idealTimeout,omitempty"`
	IdealTimeoutBackoff   *uint64                  `json:"idealTimeoutBackoff,omitempty"`
	IdealTimeoutMessage   *string                  `json:"idealTimeoutMessage,omitempty"`
	InputAudio            *DeploymentAudioProvider `json:"inputAudio,omitempty"`
	MaxSessionDuration    *uint64                  `json:"maxSessionDuration,omitempty"`
	Mistake               *string                  `json:"mistake,omitempty"`
	OutputAudio           *DeploymentAudioProvider `json:"outputAudio,omitempty"`
	PhoneOptions          *[]Metadata              `json:"phoneOptions,omitempty"`
	PhoneProviderName     *string                  `json:"phoneProviderName,omitempty"`
	Status                *string                  `json:"status,omitempty"`
	UnclearInputMessage   *string                  `json:"unclearInputMessage,omitempty"`
	UnclearInputTimeout   *float64                 `json:"unclearInputTimeout,omitempty"`
}

// AssistantProviderAgentflow defines model for AssistantProviderAgentflow.
type AssistantProviderAgentflow struct {
	AssistantId   *Uint64String           `json:"assistantId,omitempty"`
	Definition    *map[string]interface{} `json:"definition,omitempty"`
	Description   *string                 `json:"description,omitempty"`
	Id            *Uint64String           `json:"id,omitempty"`
	SchemaVersion *string                 `json:"schemaVersion,omitempty"`
	Status        *string                 `json:"status,omitempty"`
}

// AssistantProviderAgentkit defines model for AssistantProviderAgentkit.
type AssistantProviderAgentkit struct {
	AssistantId         *Uint64String      `json:"assistantId,omitempty"`
	Certificate         *string            `json:"certificate,omitempty"`
	ConnectTimeoutMs    *uint32            `json:"connectTimeoutMs,omitempty"`
	Description         *string            `json:"description,omitempty"`
	Id                  *Uint64String      `json:"id,omitempty"`
	KeepaliveTimeMs     *uint32            `json:"keepaliveTimeMs,omitempty"`
	KeepaliveTimeoutMs  *uint32            `json:"keepaliveTimeoutMs,omitempty"`
	MaxRecvMessageBytes *uint32            `json:"maxRecvMessageBytes,omitempty"`
	MaxSendMessageBytes *uint32            `json:"maxSendMessageBytes,omitempty"`
	Metadata            *map[string]string `json:"metadata,omitempty"`
	Status              *string            `json:"status,omitempty"`
	TlsServerName       *string            `json:"tlsServerName,omitempty"`
	TlsVerification     *string            `json:"tlsVerification,omitempty"`
	TransportSecurity   *string            `json:"transportSecurity,omitempty"`
	Url                 *string            `json:"url,omitempty"`
}

// AssistantProviderModel defines model for AssistantProviderModel.
type AssistantProviderModel struct {
	AssistantId           *Uint64String           `json:"assistantId,omitempty"`
	AssistantModelOptions *[]Metadata             `json:"assistantModelOptions,omitempty"`
	Description           *string                 `json:"description,omitempty"`
	Id                    *Uint64String           `json:"id,omitempty"`
	ModelProviderName     *string                 `json:"modelProviderName,omitempty"`
	Status                *string                 `json:"status,omitempty"`
	Template              *TextChatCompletePrompt `json:"template,omitempty"`
}

// AssistantProviderWebsocket defines model for AssistantProviderWebsocket.
type AssistantProviderWebsocket struct {
	AssistantId *Uint64String      `json:"assistantId,omitempty"`
	Description *string            `json:"description,omitempty"`
	Headers     *map[string]string `json:"headers,omitempty"`
	Id          *Uint64String      `json:"id,omitempty"`
	Parameters  *map[string]string `json:"parameters,omitempty"`
	Status      *string            `json:"status,omitempty"`
	Url         *string            `json:"url,omitempty"`
}

// AssistantTag defines model for AssistantTag.
type AssistantTag struct {
	AssistantId *Uint64String `json:"assistantId,omitempty"`
	Id          *Uint64String `json:"id,omitempty"`
	Tag         *[]string     `json:"tag,omitempty"`
}

// AssistantTool defines model for AssistantTool.
type AssistantTool struct {
	AssistantId      *Uint64String           `json:"assistantId,omitempty"`
	Description      *string                 `json:"description,omitempty"`
	ExecutionMethod  *string                 `json:"executionMethod,omitempty"`
	ExecutionOptions *[]Metadata             `json:"executionOptions,omitempty"`
	Fields           *map[string]interface{} `json:"fields,omitempty"`
	Id               *Uint64String           `json:"id,omitempty"`
	Name             *string                 `json:"name,omitempty"`
	Status           *string                 `json:"status,omitempty"`
}

// AssistantWebpluginDeployment defines model for AssistantWebpluginDeployment.
type AssistantWebpluginDeployment struct {
	AssistantId           *Uint64String            `json:"assistantId,omitempty"`
	Greeting              *string                  `json:"greeting,omitempty"`
	GreetingInterruptible *bool                    `json:"greetingInterruptible,omitempty"`
	Id                    *Uint64String            `json:"id,omitempty"`
	IdealTimeout          *uint64                  `json:"idealTimeout,omitempty"`
	IdealTimeoutBackoff   *uint64                  `json:"idealTimeoutBackoff,omitempty"`
	IdealTimeoutMessage   *string                  `json:"idealTimeoutMessage,omitempty"`
	InputAudio            *DeploymentAudioProvider `json:"inputAudio,omitempty"`
	MaxSessionDuration    *uint64                  `json:"maxSessionDuration,omitempty"`
	Mistake               *string                  `json:"mistake,omitempty"`
	OutputAudio           *DeploymentAudioProvider `json:"outputAudio,omitempty"`
	Status                *string                  `json:"status,omitempty"`
	Suggestion            *[]string                `json:"suggestion,omitempty"`
	UnclearInputMessage   *string                  `json:"unclearInputMessage,omitempty"`
	UnclearInputTimeout   *float64                 `json:"unclearInputTimeout,omitempty"`
}

// AssistantWhatsappDeployment defines model for AssistantWhatsappDeployment.
type AssistantWhatsappDeployment struct {
	AssistantId           *Uint64String `json:"assistantId,omitempty"`
	Greeting              *string       `json:"greeting,omitempty"`
	GreetingInterruptible *bool         `json:"greetingInterruptible,omitempty"`
	Id                    *Uint64String `json:"id,omitempty"`
	IdealTimeout          *uint64       `json:"idealTimeout,omitempty"`
	IdealTimeoutBackoff   *uint64       `json:"idealTimeoutBackoff,omitempty"`
	IdealTimeoutMessage   *string       `json:"idealTimeoutMessage,omitempty"`
	MaxSessionDuration    *uint64       `json:"maxSessionDuration,omitempty"`
	Mistake               *string       `json:"mistake,omitempty"`
	Status                *string       `json:"status,omitempty"`
	UnclearInputMessage   *string       `json:"unclearInputMessage,omitempty"`
	UnclearInputTimeout   *float64      `json:"unclearInputTimeout,omitempty"`
	WhatsappOptions       *[]Metadata   `json:"whatsappOptions,omitempty"`
	WhatsappProviderName  *string       `json:"whatsappProviderName,omitempty"`
}

// CreateAssistantApiDeploymentRequest defines model for CreateAssistantApiDeploymentRequest.
type CreateAssistantApiDeploymentRequest struct {
	AssistantId           Uint64String                    `json:"assistantId"`
	Greeting              *string                         `json:"greeting,omitempty"`
	GreetingInterruptible *bool                           `json:"greetingInterruptible,omitempty"`
	IdealTimeout          *uint64                         `json:"idealTimeout,omitempty"`
	IdealTimeoutBackoff   *uint64                         `json:"idealTimeoutBackoff,omitempty"`
	IdealTimeoutMessage   *string                         `json:"idealTimeoutMessage,omitempty"`
	InputAudio            *DeploymentAudioProviderRequest `json:"inputAudio,omitempty"`
	MaxSessionDuration    *uint64                         `json:"maxSessionDuration,omitempty"`
	Mistake               *string                         `json:"mistake,omitempty"`
	OutputAudio           *DeploymentAudioProviderRequest `json:"outputAudio,omitempty"`
	UnclearInputMessage   *string                         `json:"unclearInputMessage,omitempty"`
	UnclearInputTimeout   *float64                        `json:"unclearInputTimeout,omitempty"`
}

// CreateAssistantConfigurationRequest defines model for CreateAssistantConfigurationRequest.
type CreateAssistantConfigurationRequest struct {
	AssistantId       Uint64String `json:"assistantId"`
	ConfigurationType string       `json:"configurationType"`
	Enabled           bool         `json:"enabled"`
	Options           *[]Metadata  `json:"options,omitempty"`
	Provider          string       `json:"provider"`
}

// CreateAssistantDebuggerDeploymentRequest defines model for CreateAssistantDebuggerDeploymentRequest.
type CreateAssistantDebuggerDeploymentRequest struct {
	AssistantId           Uint64String                    `json:"assistantId"`
	Greeting              *string                         `json:"greeting,omitempty"`
	GreetingInterruptible *bool                           `json:"greetingInterruptible,omitempty"`
	IdealTimeout          *uint64                         `json:"idealTimeout,omitempty"`
	IdealTimeoutBackoff   *uint64                         `json:"idealTimeoutBackoff,omitempty"`
	IdealTimeoutMessage   *string                         `json:"idealTimeoutMessage,omitempty"`
	InputAudio            *DeploymentAudioProviderRequest `json:"inputAudio,omitempty"`
	MaxSessionDuration    *uint64                         `json:"maxSessionDuration,omitempty"`
	Mistake               *string                         `json:"mistake,omitempty"`
	OutputAudio           *DeploymentAudioProviderRequest `json:"outputAudio,omitempty"`
	UnclearInputMessage   *string                         `json:"unclearInputMessage,omitempty"`
	UnclearInputTimeout   *float64                        `json:"unclearInputTimeout,omitempty"`
}

// CreateAssistantKnowledgeRequest defines model for CreateAssistantKnowledgeRequest.
type CreateAssistantKnowledgeRequest struct {
	AssistantId                       *Uint64String `json:"assistantId,omitempty"`
	AssistantKnowledgeRerankerOptions *[]Metadata   `json:"assistantKnowledgeRerankerOptions,omitempty"`
	KnowledgeId                       *Uint64String `json:"knowledgeId,omitempty"`
	RerankerEnable                    *bool         `json:"rerankerEnable,omitempty"`
	RerankerModelProviderId           *Uint64String `json:"rerankerModelProviderId,omitempty"`
	RerankerModelProviderName         *string       `json:"rerankerModelProviderName,omitempty"`
	RetrievalMethod                   *string       `json:"retrievalMethod,omitempty"`
	ScoreThreshold                    *float32      `json:"scoreThreshold,omitempty"`
	TopK                              *uint32       `json:"topK,omitempty"`
}

// CreateAssistantPhoneDeploymentRequest defines model for CreateAssistantPhoneDeploymentRequest.
type CreateAssistantPhoneDeploymentRequest struct {
	AssistantId           Uint64String                    `json:"assistantId"`
	Greeting              *string                         `json:"greeting,omitempty"`
	GreetingInterruptible *bool                           `json:"greetingInterruptible,omitempty"`
	IdealTimeout          *uint64                         `json:"idealTimeout,omitempty"`
	IdealTimeoutBackoff   *uint64                         `json:"idealTimeoutBackoff,omitempty"`
	IdealTimeoutMessage   *string                         `json:"idealTimeoutMessage,omitempty"`
	InputAudio            *DeploymentAudioProviderRequest `json:"inputAudio,omitempty"`
	MaxSessionDuration    *uint64                         `json:"maxSessionDuration,omitempty"`
	Mistake               *string                         `json:"mistake,omitempty"`
	OutputAudio           *DeploymentAudioProviderRequest `json:"outputAudio,omitempty"`
	PhoneOptions          *[]Metadata                     `json:"phoneOptions,omitempty"`
	PhoneProviderName     string                          `json:"phoneProviderName"`
	UnclearInputMessage   *string                         `json:"unclearInputMessage,omitempty"`
	UnclearInputTimeout   *float64                        `json:"unclearInputTimeout,omitempty"`
}

// CreateAssistantProviderAgentflow defines model for CreateAssistantProviderAgentflow.
type CreateAssistantProviderAgentflow struct {
	Definition    map[string]interface{} `json:"definition"`
	SchemaVersion string                 `json:"schemaVersion"`
}

// CreateAssistantProviderAgentkit defines model for CreateAssistantProviderAgentkit.
type CreateAssistantProviderAgentkit struct {
	AgentKitUrl         string             `json:"agentKitUrl"`
	Certificate         *string            `json:"certificate,omitempty"`
	ConnectTimeoutMs    *uint32            `json:"connectTimeoutMs,omitempty"`
	KeepaliveTimeMs     *uint32            `json:"keepaliveTimeMs,omitempty"`
	KeepaliveTimeoutMs  *uint32            `json:"keepaliveTimeoutMs,omitempty"`
	MaxRecvMessageBytes *uint32            `json:"maxRecvMessageBytes,omitempty"`
	MaxSendMessageBytes *uint32            `json:"maxSendMessageBytes,omitempty"`
	Metadata            *map[string]string `json:"metadata,omitempty"`
	TlsServerName       *string            `json:"tlsServerName,omitempty"`
	TlsVerification     *string            `json:"tlsVerification,omitempty"`
	TransportSecurity   *string            `json:"transportSecurity,omitempty"`
}

// CreateAssistantProviderModel defines model for CreateAssistantProviderModel.
type CreateAssistantProviderModel struct {
	AssistantModelOptions *[]Metadata             `json:"assistantModelOptions,omitempty"`
	ModelProviderName     string                  `json:"modelProviderName"`
	Template              *TextChatCompletePrompt `json:"template,omitempty"`
}

// CreateAssistantProviderRequest defines model for CreateAssistantProviderRequest.
type CreateAssistantProviderRequest struct {
	Agentflow   *CreateAssistantProviderAgentflow `json:"agentflow,omitempty"`
	Agentkit    *CreateAssistantProviderAgentkit  `json:"agentkit,omitempty"`
	AssistantId *Uint64String                     `json:"assistantId,omitempty"`
	Description *string                           `json:"description,omitempty"`
	Model       *CreateAssistantProviderModel     `json:"model,omitempty"`
	Websocket   *CreateAssistantProviderWebsocket `json:"websocket,omitempty"`
}

// CreateAssistantProviderWebsocket defines model for CreateAssistantProviderWebsocket.
type CreateAssistantProviderWebsocket struct {
	ConnectionParameters *map[string]string `json:"connectionParameters,omitempty"`
	Headers              *map[string]string `json:"headers,omitempty"`
	WebsocketUrl         string             `json:"websocketUrl"`
}

// CreateAssistantRequest defines model for CreateAssistantRequest.
type CreateAssistantRequest struct {
	AssistantKnowledges *[]CreateAssistantKnowledgeRequest `json:"assistantKnowledges,omitempty"`
	AssistantProvider   CreateAssistantProviderRequest     `json:"assistantProvider"`
	AssistantTools      *[]CreateAssistantToolRequest      `json:"assistantTools,omitempty"`
	Description         *string                            `json:"description,omitempty"`
	Language            *string                            `json:"language,omitempty"`
	Name                string                             `json:"name"`
	Source              *string                            `json:"source,omitempty"`
	SourceIdentifier    *Uint64String                      `json:"sourceIdentifier,omitempty"`
	Tags                *[]string                          `json:"tags,omitempty"`
	Visibility          *string                            `json:"visibility,omitempty"`
}

// CreateAssistantToolRequest defines model for CreateAssistantToolRequest.
type CreateAssistantToolRequest struct {
	AssistantId      *Uint64String           `json:"assistantId,omitempty"`
	Description      *string                 `json:"description,omitempty"`
	ExecutionMethod  *string                 `json:"executionMethod,omitempty"`
	ExecutionOptions *[]Metadata             `json:"executionOptions,omitempty"`
	Fields           *map[string]interface{} `json:"fields,omitempty"`
	Name             *string                 `json:"name,omitempty"`
}

// CreateAssistantWebpluginDeploymentRequest defines model for CreateAssistantWebpluginDeploymentRequest.
type CreateAssistantWebpluginDeploymentRequest struct {
	AssistantId           Uint64String                    `json:"assistantId"`
	Greeting              *string                         `json:"greeting,omitempty"`
	GreetingInterruptible *bool                           `json:"greetingInterruptible,omitempty"`
	IdealTimeout          *uint64                         `json:"idealTimeout,omitempty"`
	IdealTimeoutBackoff   *uint64                         `json:"idealTimeoutBackoff,omitempty"`
	IdealTimeoutMessage   *string                         `json:"idealTimeoutMessage,omitempty"`
	InputAudio            *DeploymentAudioProviderRequest `json:"inputAudio,omitempty"`
	MaxSessionDuration    *uint64                         `json:"maxSessionDuration,omitempty"`
	Mistake               *string                         `json:"mistake,omitempty"`
	OutputAudio           *DeploymentAudioProviderRequest `json:"outputAudio,omitempty"`
	Suggestion            *[]string                       `json:"suggestion,omitempty"`
	UnclearInputMessage   *string                         `json:"unclearInputMessage,omitempty"`
	UnclearInputTimeout   *float64                        `json:"unclearInputTimeout,omitempty"`
}

// CreateAssistantWhatsappDeploymentRequest defines model for CreateAssistantWhatsappDeploymentRequest.
type CreateAssistantWhatsappDeploymentRequest struct {
	AssistantId           Uint64String `json:"assistantId"`
	Greeting              *string      `json:"greeting,omitempty"`
	GreetingInterruptible *bool        `json:"greetingInterruptible,omitempty"`
	IdealTimeout          *uint64      `json:"idealTimeout,omitempty"`
	IdealTimeoutBackoff   *uint64      `json:"idealTimeoutBackoff,omitempty"`
	IdealTimeoutMessage   *string      `json:"idealTimeoutMessage,omitempty"`
	MaxSessionDuration    *uint64      `json:"maxSessionDuration,omitempty"`
	Mistake               *string      `json:"mistake,omitempty"`
	UnclearInputMessage   *string      `json:"unclearInputMessage,omitempty"`
	UnclearInputTimeout   *float64     `json:"unclearInputTimeout,omitempty"`
	WhatsappOptions       *[]Metadata  `json:"whatsappOptions,omitempty"`
	WhatsappProviderName  string       `json:"whatsappProviderName"`
}

// DeploymentAudioProvider defines model for DeploymentAudioProvider.
type DeploymentAudioProvider struct {
	AudioOptions  *[]Metadata   `json:"audioOptions,omitempty"`
	AudioProvider *string       `json:"audioProvider,omitempty"`
	AudioType     *string       `json:"audioType,omitempty"`
	Id            *Uint64String `json:"id,omitempty"`
	Status        *string       `json:"status,omitempty"`
}

// DeploymentAudioProviderRequest defines model for DeploymentAudioProviderRequest.
type DeploymentAudioProviderRequest struct {
	AudioOptions  *[]Metadata `json:"audioOptions,omitempty"`
	AudioProvider string      `json:"audioProvider"`
	AudioType     *string     `json:"audioType,omitempty"`
	Status        *string     `json:"status,omitempty"`
}

// GetAllAssistantApiDeploymentResponse defines model for GetAllAssistantApiDeploymentResponse.
type GetAllAssistantApiDeploymentResponse struct {
	Code *int32                    `json:"code,omitempty"`
	Data *[]AssistantApiDeployment `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error     *Error     `json:"error,omitempty"`
	Paginated *Paginated `json:"paginated,omitempty"`
	Success   *bool      `json:"success,omitempty"`
}

// GetAllAssistantConfigurationResponse defines model for GetAllAssistantConfigurationResponse.
type GetAllAssistantConfigurationResponse struct {
	Code *int32                    `json:"code,omitempty"`
	Data *[]AssistantConfiguration `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error     *Error     `json:"error,omitempty"`
	Paginated *Paginated `json:"paginated,omitempty"`
	Success   *bool      `json:"success,omitempty"`
}

// GetAllAssistantDebuggerDeploymentResponse defines model for GetAllAssistantDebuggerDeploymentResponse.
type GetAllAssistantDebuggerDeploymentResponse struct {
	Code *int32                         `json:"code,omitempty"`
	Data *[]AssistantDebuggerDeployment `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error     *Error     `json:"error,omitempty"`
	Paginated *Paginated `json:"paginated,omitempty"`
	Success   *bool      `json:"success,omitempty"`
}

// GetAllAssistantPhoneDeploymentResponse defines model for GetAllAssistantPhoneDeploymentResponse.
type GetAllAssistantPhoneDeploymentResponse struct {
	Code *int32                      `json:"code,omitempty"`
	Data *[]AssistantPhoneDeployment `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error     *Error     `json:"error,omitempty"`
	Paginated *Paginated `json:"paginated,omitempty"`
	Success   *bool      `json:"success,omitempty"`
}

// GetAllAssistantWebpluginDeploymentResponse defines model for GetAllAssistantWebpluginDeploymentResponse.
type GetAllAssistantWebpluginDeploymentResponse struct {
	Code *int32                          `json:"code,omitempty"`
	Data *[]AssistantWebpluginDeployment `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error     *Error     `json:"error,omitempty"`
	Paginated *Paginated `json:"paginated,omitempty"`
	Success   *bool      `json:"success,omitempty"`
}

// GetAllAssistantWhatsappDeploymentResponse defines model for GetAllAssistantWhatsappDeploymentResponse.
type GetAllAssistantWhatsappDeploymentResponse struct {
	Code *int32                         `json:"code,omitempty"`
	Data *[]AssistantWhatsappDeployment `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error     *Error     `json:"error,omitempty"`
	Paginated *Paginated `json:"paginated,omitempty"`
	Success   *bool      `json:"success,omitempty"`
}

// GetAssistantApiDeploymentResponse defines model for GetAssistantApiDeploymentResponse.
type GetAssistantApiDeploymentResponse struct {
	Code *int32                  `json:"code,omitempty"`
	Data *AssistantApiDeployment `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error   *Error `json:"error,omitempty"`
	Success *bool  `json:"success,omitempty"`
}

// GetAssistantConfigurationResponse defines model for GetAssistantConfigurationResponse.
type GetAssistantConfigurationResponse struct {
	Code *int32                  `json:"code,omitempty"`
	Data *AssistantConfiguration `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error   *Error `json:"error,omitempty"`
	Success *bool  `json:"success,omitempty"`
}

// GetAssistantDebuggerDeploymentResponse defines model for GetAssistantDebuggerDeploymentResponse.
type GetAssistantDebuggerDeploymentResponse struct {
	Code *int32                       `json:"code,omitempty"`
	Data *AssistantDebuggerDeployment `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error   *Error `json:"error,omitempty"`
	Success *bool  `json:"success,omitempty"`
}

// GetAssistantPhoneDeploymentResponse defines model for GetAssistantPhoneDeploymentResponse.
type GetAssistantPhoneDeploymentResponse struct {
	Code *int32                    `json:"code,omitempty"`
	Data *AssistantPhoneDeployment `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error   *Error `json:"error,omitempty"`
	Success *bool  `json:"success,omitempty"`
}

// GetAssistantResponse defines model for GetAssistantResponse.
type GetAssistantResponse struct {
	Code *int32     `json:"code,omitempty"`
	Data *Assistant `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error   *Error `json:"error,omitempty"`
	Success *bool  `json:"success,omitempty"`
}

// GetAssistantWebpluginDeploymentResponse defines model for GetAssistantWebpluginDeploymentResponse.
type GetAssistantWebpluginDeploymentResponse struct {
	Code *int32                        `json:"code,omitempty"`
	Data *AssistantWebpluginDeployment `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error   *Error `json:"error,omitempty"`
	Success *bool  `json:"success,omitempty"`
}

// GetAssistantWhatsappDeploymentResponse defines model for GetAssistantWhatsappDeploymentResponse.
type GetAssistantWhatsappDeploymentResponse struct {
	Code *int32                       `json:"code,omitempty"`
	Data *AssistantWhatsappDeployment `json:"data,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error   *Error `json:"error,omitempty"`
	Success *bool  `json:"success,omitempty"`
}

// TextChatCompletePrompt defines model for TextChatCompletePrompt.
type TextChatCompletePrompt struct {
	Prompt          *[]TextPrompt `json:"prompt,omitempty"`
	PromptVariables *[]Variable   `json:"promptVariables,omitempty"`
}

// TextPrompt defines model for TextPrompt.
type TextPrompt struct {
	Content *string `json:"content,omitempty"`
	Role    *string `json:"role,omitempty"`
}

// UpdateAssistantConfigurationRequest defines model for UpdateAssistantConfigurationRequest.
type UpdateAssistantConfigurationRequest struct {
	ConfigurationType string      `json:"configurationType"`
	Enabled           bool        `json:"enabled"`
	Options           *[]Metadata `json:"options,omitempty"`
	Provider          string      `json:"provider"`
}

// Variable defines model for Variable.
type Variable struct {
	DefaultValue *string       `json:"defaultValue,omitempty"`
	Id           *Uint64String `json:"id,omitempty"`
	Name         *string       `json:"name,omitempty"`
	Type         *string       `json:"type,omitempty"`
}

// GetAllAssistantApiDeploymentParams defines parameters for GetAllAssistantApiDeployment.
type GetAllAssistantApiDeploymentParams struct {
	Page     *uint32 `form:"page,omitempty" json:"page,omitempty"`
	PageSize *uint32 `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Criterias JSON encoded array of Criteria objects.
	Criterias *string `form:"criterias,omitempty" json:"criterias,omitempty"`
}

// GetAllAssistantDebuggerDeploymentParams defines parameters for GetAllAssistantDebuggerDeployment.
type GetAllAssistantDebuggerDeploymentParams struct {
	Page     *uint32 `form:"page,omitempty" json:"page,omitempty"`
	PageSize *uint32 `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Criterias JSON encoded array of Criteria objects.
	Criterias *string `form:"criterias,omitempty" json:"criterias,omitempty"`
}

// GetAllAssistantPhoneDeploymentParams defines parameters for GetAllAssistantPhoneDeployment.
type GetAllAssistantPhoneDeploymentParams struct {
	Page     *uint32 `form:"page,omitempty" json:"page,omitempty"`
	PageSize *uint32 `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Criterias JSON encoded array of Criteria objects.
	Criterias *string `form:"criterias,omitempty" json:"criterias,omitempty"`
}

// GetAllAssistantWebpluginDeploymentParams defines parameters for GetAllAssistantWebpluginDeployment.
type GetAllAssistantWebpluginDeploymentParams struct {
	Page     *uint32 `form:"page,omitempty" json:"page,omitempty"`
	PageSize *uint32 `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Criterias JSON encoded array of Criteria objects.
	Criterias *string `form:"criterias,omitempty" json:"criterias,omitempty"`
}

// GetAllAssistantWhatsappDeploymentParams defines parameters for GetAllAssistantWhatsappDeployment.
type GetAllAssistantWhatsappDeploymentParams struct {
	Page     *uint32 `form:"page,omitempty" json:"page,omitempty"`
	PageSize *uint32 `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Criterias JSON encoded array of Criteria objects.
	Criterias *string `form:"criterias,omitempty" json:"criterias,omitempty"`
}

// GetAllAssistantConfigurationParams defines parameters for GetAllAssistantConfiguration.
type GetAllAssistantConfigurationParams struct {
	ConfigurationType *string `form:"configurationType,omitempty" json:"configurationType,omitempty"`
	Provider          *string `form:"provider,omitempty" json:"provider,omitempty"`
	Page              *uint32 `form:"page,omitempty" json:"page,omitempty"`
	PageSize          *uint32 `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// CreateAssistantApiDeploymentJSONRequestBody defines body for CreateAssistantApiDeployment for application/json ContentType.
type CreateAssistantApiDeploymentJSONRequestBody = CreateAssistantApiDeploymentRequest

// CreateAssistantDebuggerDeploymentJSONRequestBody defines body for CreateAssistantDebuggerDeployment for application/json ContentType.
type CreateAssistantDebuggerDeploymentJSONRequestBody = CreateAssistantDebuggerDeploymentRequest

// CreateAssistantPhoneDeploymentJSONRequestBody defines body for CreateAssistantPhoneDeployment for application/json ContentType.
type CreateAssistantPhoneDeploymentJSONRequestBody = CreateAssistantPhoneDeploymentRequest

// CreateAssistantWebpluginDeploymentJSONRequestBody defines body for CreateAssistantWebpluginDeployment for application/json ContentType.
type CreateAssistantWebpluginDeploymentJSONRequestBody = CreateAssistantWebpluginDeploymentRequest

// CreateAssistantWhatsappDeploymentJSONRequestBody defines body for CreateAssistantWhatsappDeployment for application/json ContentType.
type CreateAssistantWhatsappDeploymentJSONRequestBody = CreateAssistantWhatsappDeploymentRequest

// CreateAssistantConfigurationJSONRequestBody defines body for CreateAssistantConfiguration for application/json ContentType.
type CreateAssistantConfigurationJSONRequestBody = CreateAssistantConfigurationRequest

// UpdateAssistantConfigurationJSONRequestBody defines body for UpdateAssistantConfiguration for application/json ContentType.
type UpdateAssistantConfigurationJSONRequestBody = UpdateAssistantConfigurationRequest

// CreateAssistantJSONRequestBody defines body for CreateAssistant for application/json ContentType.
type CreateAssistantJSONRequestBody = CreateAssistantRequest
