// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"
)

// Argument defines model for Argument.
type Argument struct {
	Id    *Uint64String `json:"id,omitempty"`
	Name  *string       `json:"name,omitempty"`
	Value *string       `json:"value,omitempty"`
}

// AssistantConversation defines model for AssistantConversation.
type AssistantConversation struct {
	Arguments                    *[]Argument                            `json:"arguments,omitempty"`
	AssistantConversationMessage *[]AssistantConversationMessage        `json:"assistantConversationMessage,omitempty"`
	AssistantId                  *Uint64String                          `json:"assistantId,omitempty"`
	AssistantProviderModelId     *Uint64String                          `json:"assistantProviderModelId,omitempty"`
	Contexts                     *[]AssistantConversationContext        `json:"contexts,omitempty"`
	CreatedBy                    *Uint64String                          `json:"createdBy,omitempty"`
	CreatedDate                  *time.Time                             `json:"createdDate,omitempty"`
	Direction                    *string                                `json:"direction,omitempty"`
	Id                           *Uint64String                          `json:"id,omitempty"`
	Identifier                   *string                                `json:"identifier,omitempty"`
	Metadata                     *[]Metadata                            `json:"metadata,omitempty"`
	Metrics                      *[]Metric                              `json:"metrics,omitempty"`
	Name                         *string                                `json:"name,omitempty"`
	Options                      *[]Metadata                            `json:"options,omitempty"`
	OrganizationId               *Uint64String                          `json:"organizationId,omitempty"`
	ProjectId                    *Uint64String                          `json:"projectId,omitempty"`
	Recordings                   *[]AssistantConversationRecording      `json:"recordings,omitempty"`
	Source                       *string                                `json:"source,omitempty"`
	Status                       *string                                `json:"status,omitempty"`
	TelephonyEvents              *[]AssistantConversationTelephonyEvent `json:"telephonyEvents,omitempty"`
	UpdatedBy                    *Uint64String                          `json:"updatedBy,omitempty"`
	UpdatedDate                  *time.Time                             `json:"updatedDate,omitempty"`
	User                         *User                                  `json:"user,omitempty"`
	UserId                       *Uint64String                          `json:"userId,omitempty"`
}

// AssistantConversationContext defines model for AssistantConversationContext.
type AssistantConversationContext struct {
	AssistantConversationId *Uint64String `json:"assistantConversationId,omitempty"`
	CreatedDate             *time.Time    `json:"createdDate,omitempty"`
	Id                      *Uint64String `json:"id,omitempty"`
	Key                     *string       `json:"key,omitempty"`
	UpdatedDate             *time.Time    `json:"updatedDate,omitempty"`
	Value                   *string       `json:"value,omitempty"`
}

// AssistantConversationMessage defines model for AssistantConversationMessage.
type AssistantConversationMessage struct {
	AssistantConversationId *Uint64String `json:"assistantConversationId,omitempty"`
	Content                 *string       `json:"content,omitempty"`
	CreatedDate             *time.Time    `json:"createdDate,omitempty"`
	Id                      *Uint64String `json:"id,omitempty"`
	Role                    *string       `json:"role,omitempty"`
	UpdatedDate             *time.Time    `json:"updatedDate,omitempty"`
}

// AssistantConversationRecording defines model for AssistantConversationRecording.
type AssistantConversationRecording struct {
	AssistantConversationId  *Uint64String `json:"assistantConversationId,omitempty"`
	AssistantRecordingUrl    *string       `json:"assistantRecordingUrl,omitempty"`
	ConversationRecordingUrl *string       `json:"conversationRecordingUrl,omitempty"`
	CreatedDate              *time.Time    `json:"createdDate,omitempty"`
	Id                       *Uint64String `json:"id,omitempty"`
	UpdatedDate              *time.Time    `json:"updatedDate,omitempty"`
	UserRecordingUrl         *string       `json:"userRecordingUrl,omitempty"`
}

// AssistantConversationTelephonyEvent defines model for AssistantConversationTelephonyEvent.
type AssistantConversationTelephonyEvent struct {
	AssistantConversationId *Uint64String           `json:"assistantConversationId,omitempty"`
	CreatedDate             *time.Time              `json:"createdDate,omitempty"`
	EventType               *string                 `json:"eventType,omitempty"`
	Id                      *Uint64String           `json:"id,omitempty"`
	Payload                 *map[string]interface{} `json:"payload,omitempty"`
	Provider                *string                 `json:"provider,omitempty"`
	UpdatedDate             *time.Time              `json:"updatedDate,omitempty"`
}

// AssistantDefinition defines model for AssistantDefinition.
type AssistantDefinition struct {
	AssistantId *Uint64String `json:"assistantId,omitempty"`
	Version     *string       `json:"version,omitempty"`
}

// Criteria defines model for Criteria.
type Criteria struct {
	Key   *string `json:"key,omitempty"`
	Logic *string `json:"logic,omitempty"`
	Value *string `json:"value,omitempty"`
}

// Error Platform error response details. `errorCode` is a stable platform error code.
// See `PlatformErrorCode` for documented code/message mappings.
type Error struct {
	ErrorCode *Uint64String `json:"errorCode,omitempty"`

	// ErrorMessage Stable client-safe error message.
	ErrorMessage *string `json:"errorMessage,omitempty"`

	// HumanMessage Client-safe human-readable message.
	HumanMessage *string `json:"humanMessage,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code *int32 `json:"code,omitempty"`

	// Error Platform error response details. `errorCode` is a stable platform error code.
	// See `PlatformErrorCode` for documented code/message mappings.
	Error   *Error `json:"error,omitempty"`
	Success *bool  `json:"success,omitempty"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	Id    *Uint64String `json:"id,omitempty"`
	Key   *string       `json:"key,omitempty"`
	Value *string       `json:"value,omitempty"`
}

// Metric defines model for Metric.
type Metric struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	Value       *string `json:"value,omitempty"`
}

// Paginate defines model for Paginate.
type Paginate struct {
	Page     *uint32 `json:"page,omitempty"`
	PageSize *uint32 `json:"pageSize,omitempty"`
}

// Paginated defines model for Paginated.
type Paginated struct {
	CurrentPage *uint32 `json:"currentPage,omitempty"`
	TotalItem   *uint32 `json:"totalItem,omitempty"`
}

// PlatformErrorCode Stable platform error code.
//
// Create Assistant:
// - `1001001`: invalid request - Invalid request.
// - `1001002`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1001003`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1001004`: missing name parameter - Please provide the required name parameter.
// - `1001005`: missing assistant_provider parameter - Please provide the required assistantProvider parameter.
// - `1001006`: invalid assistant_provider parameter - Please provide exactly one assistant provider.
// - `1001007`: missing model_provider_name parameter - Please provide the required modelProviderName parameter.
// - `1001008`: missing agent_kit_url parameter - Please provide the required agentKitUrl parameter.
// - `1001009`: missing websocket_url parameter - Please provide the required websocketUrl parameter.
// - `1001010`: invalid source_identifier parameter - Please provide a valid sourceIdentifier parameter.
// - `1001011`: unable to create assistant - Unable to create assistant, please try again later.
// - `1001012`: invalid assistant provider template - Invalid assistant provider template.
// - `1001013`: unable to create assistant provider model - Unable to create assistant provider model, please try again later.
// - `1001014`: unable to attach assistant provider model - Unable to attach assistant provider model, please try again later.
// - `1001015`: unable to create assistant provider agentkit - Unable to create assistant provider agentkit, please try again later.
// - `1001016`: unable to attach assistant provider agentkit - Unable to attach assistant provider agentkit, please try again later.
// - `1001017`: unable to create assistant provider websocket - Unable to create assistant provider websocket, please try again later.
// - `1001018`: unable to attach assistant provider websocket - Unable to attach assistant provider websocket, please try again later.
// - `1001019`: invalid knowledge_id parameter - Please provide a valid knowledgeId parameter.
// - `1001020`: invalid reranker_model_provider_id parameter - Please provide a valid rerankerModelProviderId parameter.
// - `1001021`: unable to create assistant tools - Unable to create assistant tools, please try again later.
// - `1001022`: unable to create assistant knowledge - Unable to create assistant knowledge, please try again later.
// - `1001023`: unable to create assistant tags - Unable to create assistant tags, please try again.
//
// Create Phone Call:
// - `1002001`: invalid request - Invalid request.
// - `1002002`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1002003`: missing toNumber parameter - Please provide the required toNumber parameter.
// - `1002004`: invalid assistant parameter - Please provide a valid assistant.
// - `1002005`: invalid metadata parameter - Please provide valid metadata.
// - `1002006`: invalid arguments parameter - Please provide valid arguments.
// - `1002007`: invalid options parameter - Please provide valid options.
// - `1002008`: unable to initiate outbound call - Unable to initiate outbound call, please try again later.
//
// Create Bulk Phone Call:
// - `1003001`: invalid request - Invalid request.
// - `1003002`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1003003`: missing phone_calls parameter - Please provide at least one phone call.
// - `1003004`: missing toNumber parameter - Please provide the required toNumber parameter.
// - `1003005`: invalid assistant parameter - Please provide a valid assistant.
// - `1003006`: invalid metadata parameter - Please provide valid metadata.
// - `1003007`: invalid arguments parameter - Please provide valid arguments.
// - `1003008`: invalid options parameter - Please provide valid options.
// - `1003009`: unable to initiate outbound call - Unable to initiate outbound call, please try again later.
//
// Create Assistant Debugger Deployment:
// - `1004001`: invalid request - Invalid request.
// - `1004002`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1004003`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1004004`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1004005`: unable to create assistant debugger deployment - Unable to create assistant debugger deployment, please try again later.
// - `1004006`: invalid audio provider parameter - Please provide a valid audioProvider parameter.
// - `1004007`: invalid ideal_timeout parameter - Please provide idealTimeout between 5 and 120 seconds.
// - `1004008`: invalid ideal_timeout_backoff parameter - Please provide idealTimeoutBackoff between 0 and 5 times.
// - `1004009`: invalid max_session_duration parameter - Please provide maxSessionDuration between 180 and 600 seconds.
//
// Create Assistant Phone Deployment:
// - `1005001`: invalid request - Invalid request.
// - `1005002`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1005003`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1005004`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1005005`: unable to create assistant phone deployment - Unable to create assistant phone deployment, please try again later.
// - `1005006`: invalid audio provider parameter - Please provide a valid audioProvider parameter.
// - `1005007`: invalid ideal_timeout parameter - Please provide idealTimeout between 5 and 120 seconds.
// - `1005008`: invalid ideal_timeout_backoff parameter - Please provide idealTimeoutBackoff between 0 and 5 times.
// - `1005009`: invalid max_session_duration parameter - Please provide maxSessionDuration between 180 and 600 seconds.
// - `1005010`: missing phone_provider_name parameter - Please provide the required phoneProviderName parameter.
//
// Create Assistant API Deployment:
// - `1006001`: invalid request - Invalid request.
// - `1006002`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1006003`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1006004`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1006005`: unable to create assistant api deployment - Unable to create assistant api deployment, please try again later.
// - `1006006`: invalid audio provider parameter - Please provide a valid audioProvider parameter.
// - `1006007`: invalid ideal_timeout parameter - Please provide idealTimeout between 5 and 120 seconds.
// - `1006008`: invalid ideal_timeout_backoff parameter - Please provide idealTimeoutBackoff between 0 and 5 times.
// - `1006009`: invalid max_session_duration parameter - Please provide maxSessionDuration between 180 and 600 seconds.
//
// Create Assistant Webplugin Deployment:
// - `1007001`: invalid request - Invalid request.
// - `1007002`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1007003`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1007004`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1007005`: unable to create assistant webplugin deployment - Unable to create assistant webplugin deployment, please try again later.
// - `1007006`: invalid audio provider parameter - Please provide a valid audioProvider parameter.
// - `1007007`: invalid ideal_timeout parameter - Please provide idealTimeout between 5 and 120 seconds.
// - `1007008`: invalid ideal_timeout_backoff parameter - Please provide idealTimeoutBackoff between 0 and 5 times.
// - `1007009`: invalid max_session_duration parameter - Please provide maxSessionDuration between 180 and 600 seconds.
//
// Create Assistant WhatsApp Deployment:
// - `1008001`: invalid request - Invalid request.
// - `1008002`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1008003`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1008004`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1008005`: unable to create assistant whatsapp deployment - Unable to create assistant whatsapp deployment, please try again later.
// - `1008006`: invalid ideal_timeout parameter - Please provide idealTimeout between 5 and 120 seconds.
// - `1008007`: invalid ideal_timeout_backoff parameter - Please provide idealTimeoutBackoff between 0 and 5 times.
// - `1008008`: invalid max_session_duration parameter - Please provide maxSessionDuration between 180 and 600 seconds.
// - `1008009`: missing whatsapp_provider_name parameter - Please provide the required whatsappProviderName parameter.
//
// Get Assistant Debugger Deployment:
// - `1009001`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1009002`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1009003`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1009004`: unable to get assistant debugger deployment - Unable to get assistant debugger deployment, please try again later.
//
// Get Assistant Phone Deployment:
// - `1010001`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1010002`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1010003`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1010004`: unable to get assistant phone deployment - Unable to get assistant phone deployment, please try again later.
//
// Get Assistant API Deployment:
// - `1011001`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1011002`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1011003`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1011004`: unable to get assistant api deployment - Unable to get assistant api deployment, please try again later.
//
// Get Assistant Webplugin Deployment:
// - `1012001`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1012002`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1012003`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1012004`: unable to get assistant webplugin deployment - Unable to get assistant webplugin deployment, please try again later.
//
// Get Assistant WhatsApp Deployment:
// - `1013001`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1013002`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1013003`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1013004`: unable to get assistant whatsapp deployment - Unable to get assistant whatsapp deployment, please try again later.
//
// Get All Assistant Debugger Deployment:
// - `1014001`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1014002`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1014003`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1014004`: invalid request - Invalid request.
// - `1014005`: unable to get assistant debugger deployments - Unable to get assistant debugger deployments, please try again later.
//
// Get All Assistant Phone Deployment:
// - `1015001`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1015002`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1015003`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1015004`: invalid request - Invalid request.
// - `1015005`: unable to get assistant phone deployments - Unable to get assistant phone deployments, please try again later.
//
// Get All Assistant API Deployment:
// - `1016001`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1016002`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1016003`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1016004`: invalid request - Invalid request.
// - `1016005`: unable to get assistant api deployments - Unable to get assistant api deployments, please try again later.
//
// Get All Assistant Webplugin Deployment:
// - `1017001`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1017002`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1017003`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1017004`: invalid request - Invalid request.
// - `1017005`: unable to get assistant webplugin deployments - Unable to get assistant webplugin deployments, please try again later.
//
// Get All Assistant WhatsApp Deployment:
// - `1018001`: unauthenticated request - Unauthenticated request, please try again with valid authentication.
// - `1018002`: missing authentication scope - Unauthenticated request, please try again with valid authentication.
// - `1018003`: invalid assistant_id parameter - Please provide a valid assistantId parameter.
// - `1018004`: invalid request - Invalid request.
// - `1018005`: unable to get assistant whatsapp deployments - Unable to get assistant whatsapp deployments, please try again later.
type PlatformErrorCode = string

// Uint64String defines model for Uint64String.
type Uint64String = string

// User defines model for User.
type User struct {
	CreatedDate *time.Time    `json:"createdDate,omitempty"`
	Email       *string       `json:"email,omitempty"`
	Id          *Uint64String `json:"id,omitempty"`
	Name        *string       `json:"name,omitempty"`
	Role        *string       `json:"role,omitempty"`
	Status      *string       `json:"status,omitempty"`
}
