ALTER TABLE public.external_audits VALIDATE CONSTRAINT audit_created_actor_pair;
ALTER TABLE public.external_audits VALIDATE CONSTRAINT audit_updated_actor_pair;
ALTER TABLE public.external_audit_metadata VALIDATE CONSTRAINT audit_created_actor_pair;
ALTER TABLE public.external_audit_metadata VALIDATE CONSTRAINT audit_updated_actor_pair;
