service_name: "endpoint-api"
service_id: 9005
host: "0.0.0.0"
port: 9005
log_level: "debug"
secret: "rpd_pks"
env: "development"

postgres:
  host: "postgres"
  port: 5432
  db_name: "endpoint_db"
  auth:
    user: "rapida_user"
    password: "rapida_db_password"
  max_open_connection: 10
  max_ideal_connection: 10
  ssl_mode: "disable"
  slc_cache:
    host: "redis"
    port: 6379
    db: 1
    max_connection: 10

redis:
  host: "redis"
  port: 6379
  db: 0
  max_connection: 5
  auth:
    user: ""
    password: ""

asset_store:
  storage_type: "local"
  storage_path_prefix: "/app/rapida-data/assets/endpoint"

integration:
  host: "integration-api:9004"
endpoint:
  host: "endpoint-api:9005"
assistant:
  host: "assistant-api:9007"
web:
  host: "web-api:9001"
document:
  host: "http://document-api:9010"
ui:
  host: "https://localhost:3000"
