#!/bin/sh
set -eu

NATIVE_DEPS_LOCK=${NATIVE_DEPS_LOCK:-/app/docker/assistant-api/native-deps.lock}

if [ ! -f "$NATIVE_DEPS_LOCK" ]; then
  echo "native dependency lock not found: $NATIVE_DEPS_LOCK" >&2
  exit 1
fi

if grep -Ev '^(#.*|[A-Z0-9_]+=[A-Za-z0-9_./:@+-]+|[[:space:]]*)$' "$NATIVE_DEPS_LOCK" >/dev/null; then
  echo "native dependency lock contains unsupported syntax" >&2
  exit 1
fi

# shellcheck disable=SC1090
. "$NATIVE_DEPS_LOCK"

required_vars='BUILDER_IMAGE BUILDER_DIGEST RUNTIME_IMAGE RUNTIME_DIGEST DEBIAN_SNAPSHOT DEBIAN_ARCH ONNX_PYTHON_VERSION ONNX_PYTHON_URL ONNX_PYTHON_SHA256 NUMPY_PYTHON_VERSION NUMPY_PYTHON_URL NUMPY_PYTHON_SHA256 PROTOBUF_PYTHON_VERSION PROTOBUF_PYTHON_URL PROTOBUF_PYTHON_SHA256 LIVEKIT_EN_REVISION LIVEKIT_EN_MODEL_SHA256 LIVEKIT_TOKENIZER_SHA256 LIVEKIT_INTL_REVISION LIVEKIT_INTL_MODEL_SHA256 PIPECAT_REVISION PIPECAT_MODEL_SHA256 TEN_VAD_ARCH TEN_VAD_LIBRARY_SHA256 GOVULNCHECK_VERSION'
for required_var in $required_vars; do
  eval "required_value=\${$required_var:-}"
  if [ -z "$required_value" ]; then
    echo "native dependency lock is missing $required_var" >&2
    exit 1
  fi
done

export BUILDER_IMAGE BUILDER_DIGEST RUNTIME_IMAGE RUNTIME_DIGEST
export DEBIAN_SNAPSHOT DEBIAN_ARCH
export ONNX_PYTHON_VERSION ONNX_PYTHON_URL ONNX_PYTHON_SHA256
export NUMPY_PYTHON_VERSION NUMPY_PYTHON_URL NUMPY_PYTHON_SHA256
export PROTOBUF_PYTHON_VERSION PROTOBUF_PYTHON_URL PROTOBUF_PYTHON_SHA256
export LIVEKIT_EN_REVISION LIVEKIT_EN_MODEL_SHA256 LIVEKIT_TOKENIZER_SHA256
export LIVEKIT_INTL_REVISION LIVEKIT_INTL_MODEL_SHA256
export PIPECAT_REVISION PIPECAT_MODEL_SHA256
export TEN_VAD_ARCH TEN_VAD_LIBRARY_SHA256 GOVULNCHECK_VERSION
